/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pogoclass_finger_print_EchoPrintLib */

#ifndef _Included_com_pogoclass_finger_print_EchoPrintLib
#define _Included_com_pogoclass_finger_print_EchoPrintLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pogoclass_finger_print_EchoPrintLib
 * Method:    getEchoPrint
 * Signature: ([FII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pogoclass_finger_1print_EchoPrintLib_getEchoPrint
  (JNIEnv *, jobject, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
